import '@dronten/assets/src/reset.css'
import { Banner as DrontenBanner } from '@dronten/components-react/src'
import { BannerType } from '@dronten/components-react/src/Banner'
import '@dronten/design-tokens/dist/index.css'
import '@dronten/font/src/index.scss'
import type { Metadata } from 'next'
import Script from 'next/script'
import * as React from 'react'
import Footer from '../components/Footer'
import Navbar from '../components/NavBar'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <>
      <Script src="https://kit.fontawesome.com/8442ade4bd.js" />
      <html lang="en">
        <body className="dronten-theme">
          <Navbar />
          <div className="container">
            <DrontenBanner
              title="Developer nota:"
              description="Deze website is met Next.js gebouwd"
              imageUrl="/favicon.ico"
              bannerType={BannerType.info}
            />
          </div>
          {children}
          <Footer />
        </body>
      </html>
    </>
  )
}
